Adding some notes for enabling vf-lag with ovs forwarder
Mellanox/containerized-ovs-forwarder pull request #5
Opened 2020-07-09 09:08 UTC by wmousa

2020-07-09 09:13 UTC, wmousa commented
@moshe010

2020-07-09 12:52 UTC, moshe010 requested changes

2020-07-09 12:52 UTC, moshe010 commented on README.md
> +      - Create vfs on both mlnx ports
let write the exact command that they will need to run. It better to add this as section

2020-07-28 06:02 UTC, moshe010 approved these changes

2020-07-28 06:02 UTC, merged