Add a service to start ovs forwarder container after reboot
Mellanox/containerized-ovs-forwarder pull request #8
Opened 2020-09-23 09:36 UTC by wmousa

2020-09-29 00:03 UTC, moshe010 requested changes
remove the Start OVS container section and let the ovs_forwarder_container_service_create.sh 
puth the service file and start it. 
you should also rename the script ovs_forwarder_container_service_create.sh to create_ovs_forwarder.sh

2020-10-05 00:01 UTC, moshe010 requested changes
will "https://github.com/Mellanox/containerized-ovs-forwarder/blob/master/container_create.sh" workon tripleo? 
Can we have 1 script that create the container and install the service script?

2020-10-05 00:01 UTC, moshe010 commented on openstack/ovs_forwarder_container_service_create.sh
> +ExecStart=/usr/bin/podman start $OVS_FORWARDER_CONTAINER_NAME
/usr/bin/podman  this will work only on tripleo r Centos8. Please add it as option to config

2020-10-05 09:28 UTC, wmousa commented
> will "https://github.com/Mellanox/containerized-ovs-forwarder/blob/master/container_create.sh" workon tripleo?
Not directly, we should move to podman in tripleo, so there should be two changes
docker create  => podman create
--restart unless-stopped => --restart always
> Can we have 1 script that create the container and install the service script?
The ovs_forwarder_container service depends on sriov_bind.service which is now only part of os-net-config in tripleo
So, I don't think it's a good idea to do it in one script

2020-11-08 10:44 UTC, moshe010 approved these changes

2020-11-08 10:44 UTC, merged